version: "3.5"
services:
  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    # environment:
    #   - ENV=development
    #   - PORT=5000
    #   - DB=mongodb://mongodb:27017/notaveldev
    #   - PYTHONUNBUFFERED=1
    env_file:
      - flask.env
    depends_on:
      - postgres
  postgres:
    image: postgres:12.2
    container_name: "postgres"
    # environment:
    #   - MONGO_DATA_DIR=/usr/data/db
    #   - MONGO_LOG_DIR=/dev/null
    env_file:
      - db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
# networks:
#   default:
#     name: flask
volumes:
  postgres_data:
