openapi: "3.0.2"
info:
  title: Notável app REST API
  version: "1.0.0"
servers:
  - url: https://api.server.test/api/v1

components:
  schemas:
    Project:
      type: object
      properties:
        id:
          type: string
        user_id:
          type: string
        name:
          type: string
        parent_project_id:
          type: string
    BulletPoint:
      type: object
      required:
        - type
      properties:
        id:
          type: string
        type:
          type: string
        user_id:
          type: string
        content:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    Task:
      allOf:
        - $ref: "#/components/schemas/BulletPoint"
        - type: object
          required:
            - type
          properties:
            due_at:
              type: string
              format: date-time
            completed:
              type: boolean
    Note:
      type: object
      properties:
        id:
          type: string
        user_id:
          type: string
        title:
          type: string
          example: Creating Notes
        created_at:
          type: string
          format: date-time
        project:
          type: string
          example: Personal
        tags:
          type: array
          items:
            type: string
          example: ["api", "swagger"]
        is_deleted:
          type: boolean
        content:
          type: array
          items:
            anyOf:
              - $ref: "#/components/schemas/BulletPoint"
              - $ref: "#/components/schemas/Task"
            discriminator:
              propertyName: type
paths:
  /tasks:
    get:
      tags:
        - Tasks
      summary: Get all tasks
      operationId: views.tasks.get_tasks
      parameters:
        - in: query
          name: project_id
          schema:
            type: string
          description: Id of project
        - in: query
          name: user_id
          schema:
            type: string
          description: Id of user
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
    post:
      tags:
        - Tasks
      summary: Create new task
      operationId: views.tasks.create_task
      requestBody:
        description: Task object to create.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
        required: true
      responses:
        "201":
          description: "successful operation"

    put:
      tags:
        - Tasks
      summary: Update new task
      operationId: views.tasks.update_task
      requestBody:
        description: Task object to update.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"

  /tasks/{task-id}:
    parameters:
      - in: path
        name: task-id
        schema:
          type: string
        description: Id of task
        required: true
    get:
      tags:
        - Tasks
      summary: Get task by id
      operationId: views.tasks.get_task
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
    delete:
      tags:
        - Tasks
      summary: Delete single task by id
      operationId: views.tasks.delete_task
      description: Changes the value of `is_deleted` to `true`
      responses:
        "200":
          description: OK
  /projects:
    get:
      tags:
        - Projects
      summary: Get all projects using query parameters
      parameters:
        - in: query
          name: user_id
          schema:
            type: string
            description: Id of user.
      operationId: views.projects.get_projects
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Project"
    post:
      tags:
        - Projects
      summary: Create new project
      operationId: views.projects.create_project
      requestBody:
        description: Note object to create.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Project"
        required: true
      responses:
        "201":
          description: "successful operation"
    put:
      tags:
        - Projects
      summary: Update existing project
      operationId: views.projects.update_project
      requestBody:
        description: Project object to be updated.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Project"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
  /projects/{project-id}:
    get:
      tags:
        - Projects
      summary: Get project by id
      operationId: views.projects.get_project
      parameters:
        - in: path
          name: project-id
          schema:
            type: string
          description: Id of project
          required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
    delete:
      tags:
        - Projects
      summary: Delete selected project
      operationId: views.projects.delete_project
      parameters:
        - in: path
          name: project-id
          schema:
            type: string
          description: Id of project
          required: true
      description: Changes the value of `is_deleted` to `true`
      responses:
        "200":
          description: OK

  /notes:
    post:
      tags:
        - Notes
      summary: Create new note
      operationId: views.notes.create_note
      requestBody:
        description: Note object to create.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Note"
        required: true
      responses:
        "201":
          description: "successful operation"
    put:
      tags:
        - Notes
      summary: Update existing note
      operationId: views.notes.update_note
      requestBody:
        description: Note object to be updated.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Note"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Note"
    get:
      tags:
        - Notes
      summary: Get all notes using query parameters.
      operationId: views.notes.get_notes
      parameters:
        - in: query
          name: user
          schema:
            type: string
          description: Id of the user.
        - in: query
          name: project
          schema:
            type: string
          description: Project name to filter by
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Note"
  /notes/{note-id}:
    get:
      tags:
        - Notes
      summary: Get note by id
      operationId: views.notes.get_note
      parameters:
        - in: path
          name: note-id
          schema:
            type: string
          required: true
          description: Id of the note to get.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Note"
    delete:
      tags:
        - Notes
      summary: Soft-delete note from store.
      operationId: views.notes.delete_note
      parameters:
        - in: path
          name: note-id
          schema:
            type: string
          required: true
          description: Id of the note to get.
      description: Changes the value of `is_deleted` to `true`.
      responses:
        "200":
          description: "sucessful operation"
