openapi: "3.0.2"
info:
  title: Notável app REST API
  version: "1.0.0"
servers:
  - url: https://api.server.test/api/v1
components:
  schemas:
    Project:
      type: object
      properties:
        id:
          type: string
        user_id:
          type: string
        name:
          type: string
        parent_project_id:
          type: string
    Bullet:
      type: object
      properties:
        id:
          type: string
        parent_notes:
          type: array
          items:
            type: string
        type:
          type: string
        user_id:
          type: string
        content:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    Task:
      allOf:
        - $ref: "#/components/schemas/Bullet"
        - type: object
          properties:
            due_at:
              type: string
              format: date-time
            completed:
              type: boolean
    Note:
      type: object
      properties:
        id:
          type: string
        user_id:
          type: string
        title:
          type: string
          example: Creating Notes
        created_at:
          type: string
          format: date-time
        project:
          type: string
          example: Personal
        tags:
          type: array
          items:
            type: string
          example: ["api", "swagger"]
        is_deleted:
          type: boolean
        content:
          type: array
          items:
            anyOf:
              - $ref: "#/components/schemas/Bullet"
              - $ref: "#/components/schemas/Task"
            discriminator:
              propertyName: type
paths:
  /tasks:
    get:
      tags:
        - Tasks
      summary: Get all tasks
      parameters:
        - in: query
          name: project_id
          schema:
            type: string
          description: Id of project
        - in: query
          name: user_id
          schema:
            type: string
          description: Id of user
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
    post:
      tags:
        - Tasks
      summary: Create new task
      requestBody:
        description: Task object to create.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
        required: true
      responses:
        "201":
          description: "successful operation"
  /tasks/{task_id}:
    parameters:
      - in: path
        name: task_id
        schema:
          type: string
        description: Id of task
        required: true
    get:
      tags:
        - Tasks
      summary: Get task by id
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
    put:
      tags:
        - Tasks
      summary: Update new task
      requestBody:
        description: Task object to update.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
    delete:
      tags:
        - Tasks
      summary: Delete single task by id
      description: Changes the value of `is_deleted` to `true`
      responses:
        "200":
          description: OK
  /bullets:
    get:
      tags:
        - Bullet Points
      summary: Get all bullet points.
      parameters:
        - in: query
          name: note_id
          schema:
            type: string
          description: Id of note
        - in: query
          name: type
          schema:
            type: string
            enum:
              - bullet
              - task
              - idea
          description: Bullet point type
        - in: query
          name: project_id
          schema:
            type: string
          description: Project id
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Bullet"
    post:
      tags:
        - Bullet Points
      summary: Create new bullet point
      requestBody:
        description: BulletPoint object to create
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Bullet"
        required: true
      responses:
        "201":
          description: OK
  /bullets/{bullet_id}:
    parameters:
      - in: path
        name: bullet_id
        schema:
          type: string
        description: Id bullet point
        required: true
    get:
      tags:
        - Bullet Points
      summary: Get bullet point by id
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Bullet"
    put:
      tags:
        - Bullet Points
      summary: Update bullet point
      requestBody:
        description: BulletPoint object to update
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Bullet"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Bullet"
    delete:
      tags:
        - Bullet Points
      summary: Delete single bullet point by id
      description: Changes the value of `is_deleted` to `true`
      responses:
        "200":
          description: OK
  /projects:
    get:
      tags:
        - Projects
      summary: Get all projects using query parameters
      parameters:
        - in: query
          name: user_id
          schema:
            type: string
            description: Id of user.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Project"
    post:
      tags:
        - Projects
      summary: Create new project
      requestBody:
        description: Note object to create.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Project"
        required: true
      responses:
        "201":
          description: "successful operation"
  /projects/{project_id}:
    parameters:
      - in: path
        name: project_id
        schema:
          type: string
        description: Id of project
        required: true
    get:
      tags:
        - Projects
      summary: Get project by id
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
    put:
      tags:
        - Projects
      summary: Update existing project
      requestBody:
        description: Project object to be updated.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Project"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
    delete:
      tags:
        - Projects
      summary: Delete selected project
      parameters:
        - in: path
          name: project_id
          schema:
            type: string
          description: Id of project
          required: true
      description: Changes the value of `is_deleted` to `true`
      responses:
        "200":
          description: OK
  /notes:
    post:
      tags:
        - Notes
      summary: Create new note
      requestBody:
        description: Note object to create.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Note"
        required: true
      responses:
        "201":
          description: "successful operation"
    get:
      tags:
        - Notes
      summary: Get all notes using query parameters.
      parameters:
        - in: query
          name: user
          schema:
            type: string
          description: Id of the user.
        - in: query
          name: project
          schema:
            type: string
          description: Project name to filter by
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Note"
  /notes/{note_id}:
    parameters:
      - in: path
        name: note_id
        schema:
          type: string
        required: true
        description: Id of the note to get.
    get:
      tags:
        - Notes
      summary: Get note by id
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Note"
    put:
      tags:
        - Notes
      summary: Update existing note
      requestBody:
        description: Note object to be updated.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Note"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Note"
    delete:
      tags:
        - Notes
      summary: Soft-delete note from store.
      parameters:
        - in: path
          name: note_id
          schema:
            type: string
          required: true
          description: Id of the note to get.
      description: Changes the value of `is_deleted` to `true`.
      responses:
        "200":
          description: "sucessful operation"
